---
apiVersion: v1
kind: Secret
metadata:
  name: ops-manager-admin-secret
  namespace: mongo
type: Opaque
stringData:
  Username: john@example.com
  # 8 characters minimum
  # 1 number, 1 letter
  # 1 special character
  Password: Passw0rd.
  FirstName: John
  LastName: Appleseed
---
apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: ops-manager
  namespace: mongo
spec:
  externalConnectivity:
    type: LoadBalancer
  applicationDatabase:
    podSpec:
      cpu: 1
    members: 3
    version: 5.0.14-ent
  configuration:
    mms.fromEmailAddr: admin@thecompany.com
  adminCredentials: ops-manager-admin-secret
  version: 6.0.3

