apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: mongodb-cluster
  namespace: mongo
spec:
  type: Standalone
  # the name of the secret in 1-ops-manager-config-secret.yaml
  credentials: mongo-ops-manager-admin-key
  # the name of the cm in 1-ops-manager-config-secret.yaml
  opsManager:
    configMapRef:
      name: ops-manager-mongo-config
  version: 4.4.5-ent
  security:
    authentication:
      enabled: true
      modes:
        - SCRAM
  #   tls:
  #     enabled: true
  #     ca: custom-ca