---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-admin-user-password
  namespace: mongo
type: Opaque
stringData:
  password: cGFzc3dvcmQ=
  # echo -n "password" | base64
---
apiVersion: mongodb.com/v1
kind: MongoDBUser
metadata:
  name: mongo-admin-user
  namespace: mongo
spec:
  passwordSecretKeyRef:
    name: mongo-admin-user-password
    # Match to metadata.name of the User Secret
    key: password
  username: admin
  db: admin
  # authentication database
  mongodbResourceRef:
    name: mongodb-cluster
    # Match to MongoDB resource using authentication
  roles:
    - db: admin
      name: readWrite
    - db: admin
      name: userAdminAnyDatabase