---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-extra-user-password
  namespace: mongo
type: Opaque
stringData:
  password: password
---
apiVersion: mongodb.com/v1
kind: MongoDBUser
metadata:
  name: mongo-extra-user
  namespace: mongo
spec:
  passwordSecretKeyRef:
    name: mongo-extra-user-password
    # Match to metadata.name of the User Secret
    key: password
  username: user1
  db: extradb
  # authentication database
  mongodbResourceRef:
    name: mongodb-cluster
    # Match to MongoDB resource using authentication
  roles:
    - db: extradb
      name: readWrite